# Generated by Django 3.1.2 on 2020-12-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201215_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_scores',
            field=models.IntegerField(default=0, verbose_name='product_scores'),
        ),
    ]
