# Generated by Django 3.1.2 on 2020-12-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201215_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, to='store.Product', verbose_name='products'),
        ),
    ]
