# Generated by Django 3.1.2 on 2020-12-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_like_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
