# Generated by Django 3.1.2 on 2020-12-15 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('first_name', models.CharField(max_length=80, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=80, verbose_name='first_name')),
                ('melli_code', models.IntegerField(db_index=True, unique=True, verbose_name='melli_code')),
                ('avatar', models.ImageField(upload_to='profile/image', verbose_name='avatar')),
                ('mobile_number', models.CharField(db_index=True, max_length=13, verbose_name='mobile_number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', related_query_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('postal_code', models.IntegerField(blank=True, null=True, verbose_name='postal_code')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', related_query_name='user_addresses', to='account.userprofile', verbose_name='Address')),
            ],
        ),
    ]
