# Generated by Django 3.1.2 on 2020-12-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraddress_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='melli_code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='melli_code'),
        ),
    ]
